# linters list
ENABLE_LINTERS:
  - YAML_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - GROOVY_NPM_GROOVY_LINT
  - JAVASCRIPT_ES
  - DOCKERFILE_HADOLINT
  - JSON_PRETTIER
  - JAVA_CHECKSTYLE

# generic config
SHOW_ELAPSED_TIME: true
PRINT_ALPACA: false

# Linter-specific config
GROOVY_NPM_GROOVY_LINT_ARGUMENTS: --failon error