version: '3.9'

services:
  zeebe:
    image: camunda/zeebe:8.1.6
    environment:
      ZEEBE_LOG_LEVEL: debug
    ports:
      - "26500:26500"
      - "9600:9600"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9600/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m30s

  zeebe_ops:
    image: oaftech.azurecr.io/phee-ns/phee-zeebe-ops:v1.0.1
    ports:
      - "5001:5000"
    environment:
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      LOGGING_LEVEL_ROOT: INFO
    depends_on:
      zeebe:
        condition: service_healthy

  channel-connector:
    image: oaftech.azurecr.io/phee-ns/ph-ee-connector-channel:v1.1.0
    ports:
      - "5002:5000"
    environment:
      DFSPIDS: oaf,oafrw,rw-oaf
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_PATTERN_CONSOLE: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
      MPESA_NOTIFICATION_FAILURE_ENABLED: false
      MPESA_NOTIFICATION_SUCCESS_ENABLED: false
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      BPMN_FLOW_MOMO-FLOW: "momo_flow_{ams}-{dfspid}"
    depends_on:
      zeebe:
        condition: service_healthy

  roster-connector:
    image: oaftech.azurecr.io/phee-ns/ph-ee-connector-ams-pesa:v1.2.1
    ports:
      - "5003:5000"
    environment:
      AMS_LOCAL_ENABLED: false
      AMS_LOCAL_TIMEOUT: 60000
      PESACORE_BASE-URL: https://qaoperations01.oneacrefund.org
      PESACORE_AUTH-HEADER: PaymentHubTest
      PESACORE_ENDPOINT_VERIFICATION: /api/paymentHub/Verification
      PESACORE_ENDPOINT_CONFIRMATION: /api/paymentHub/Confirmation
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_PATTERN_CONSOLE: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

    depends_on:
      zeebe:
        condition: service_healthy

  mtn-rw-connector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    environment:
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
    depends_on:
      zeebe:
        condition: service_healthy