version: '3.9'

networks:
  zeebe_network:
    driver: bridge
services:
  zeebe:
    container_name: zeebe_broker
    image: ghcr.io/camunda-community-hub/zeebe-with-hazelcast-exporter:8.0.5
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9600/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    networks:
      - zeebe_network

  simple-monitor-in-memory:
    container_name: zeebe-simple-monitor-in-memory
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.4.1
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8082"
    depends_on:
      zeebe:
        condition: service_healthy
    networks:
      - zeebe_network
    profiles:
      - in-memory

  channel-connector:
    image: oaftech.azurecr.io/phee-ns/ph-ee-connector-channel:v1.4.2
    ports:
      - "5002:8080"
    environment:
      AMS_GROUPS_0__IDENTIFIER: FINERACTACCOUNTID
      AMS_GROUPS_0__VALUE: mtnfineract
      DFSPIDS: oaf,oafrw,rw-oaf
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_PATTERN_CONSOLE: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
      MPESA_NOTIFICATION_FAILURE_ENABLED: false
      MPESA_NOTIFICATION_SUCCESS_ENABLED: false
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      BPMN_FLOW_MOMO-FLOW: "momo_flow_{ams}-{dfspid}"
    depends_on:
      zeebe:
        condition: service_healthy
    networks:
      - zeebe_network

  fineract-connector:
    image: oaftech.azurecr.io/oneacrefund/ph-ee-connector-ams-fineract:0.0.1-SNAPSHOT.2023.04.26.1
    ports:
      - "5003:5000"
    environment:
      AMS_LOCAL_ENABLED: true
      FINERACT_BASE-URL: https://loans.qa.oneacrefund.org/fineract-provider/api/v1
      LOGGING_LEVEL_ROOT: INFO
      SPRING_PROFILES_ACTIVE:
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      LOGGING_PATTERN_CONSOLE: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
    depends_on:
      zeebe:
        condition: service_healthy
    networks:
      - zeebe_network

  mtn-rw-connector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    environment:
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
    depends_on:
      zeebe:
        condition: service_healthy
    networks:
      - zeebe_network
  zeebe_ops:
    image: oaftech.azurecr.io/phee-ns/phee-zeebe-ops:v1.0.1
    ports:
      - "5001:5000"
    environment:
      ZEEBE_BROKER_CONTACTPOINT: zeebe:26500
      LOGGING_LEVEL_ROOT: INFO
    depends_on:
      zeebe:
        condition: service_healthy
    networks:
      - zeebe_network