version: "3"

***REMOVED***
  zeebe_network:

volumes:
  zeebe_data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

***REMOVED***
  zeebe:
    image: camunda/zeebe:1.1.0
***REMOVED***
      - ZEEBE_LOG_LEVEL=debug
      - ZEEBE_BROKER_EXPORTERS_KAFKA_CLASSNAME=hu.dpc.rt.kafkastreamer.exporter.KafkaExporter
      - ZEEBE_BROKER_EXPORTERS_KAFKA_JARPATH=/exporter.jar
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_JARPATH=/exporter.jar
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=hu.dpc.rt.kafkastreamer.exporter.NoOpExporter
***REMOVED***
      - "26500:26500"
      - "9600:9600"
    volumes:
      - zeebe_data:/usr/local/zeebe/data
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
      - /Users/sabinsheja/Documents/Work/PymentHub/test/ph-ee-exporter/kafka-clients-2.4.0.jar:/usr/local/zeebe/lib/kafka-clients-2.4.0.jar
      - /Users/sabinsheja/Documents/Work/PymentHub/test/ph-ee-exporter/target/exporter-1.0.0-SNAPSHOT.jar:/exporter.jar
    ***REMOVED***
      - zeebe_network

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
***REMOVED***
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
***REMOVED***
      - ALLOW_ANONYMOUS_LOGIN=yes
    ***REMOVED***
      - zeebe_network

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:2
***REMOVED***
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
***REMOVED***
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper
    ***REMOVED***
      - zeebe_network

  zeebe_ops:
    image: oaftech.azurecr.io/phee-ns/phee-zeebe-ops:v1.0.1
***REMOVED***
      - "5001:5000"
***REMOVED***
***REMOVED***
***REMOVED***
    depends_on:
      - zeebe
    ***REMOVED***
      - zeebe_network
