on:
  push:
    branches:
      - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh pr create -B develop -H main -t "Main backMerge" -b "sync main with develop" --reviewer one-acre-fund/services-development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}